### ISSUE TITLE
missing items causes CSV to fail

### ISSUE THREAD

**Issue by codexnubes** [charneykaye/trello2pivotal#1]
Error! TypeError: Cannot read property 'name' of undefined
    at App.cardLabelList (/Users/myrrh/Downloads/trello2pivotal/lib/trello2pivotal.js:153:54)
    at App.writePivotalTrackerRow (/Users/myrrh/Downloads/trello2pivotal/lib/trello2pivotal.js:76:31)
    at App.run (/Users/myrrh/Downloads/trello2pivotal/lib/trello2pivotal.js:57:18)
    at Object.<anonymous> (/Users/myrrh/Downloads/trello2pivotal/main.js:6:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)

When items are missing EG labels, lists, checklist the script fails

**Comment by charneykaye** [comment]
Great catch @codexnubes 

Want to put together a PR to fix this? :heart:

**Comment by codexnubes** [comment]
if I wrote JS I would. 

I added 

```
function isNotEmpty(obj) {
  for (var key in obj)
    if(obj.hasOwnProperty(key))
      return true;
  return false;
}

function cacheMembers(obj, attr) {
    let memberObjectsKeyedById = {};
    if(isNotEmpty(obj[attr])) { .. }
```

to each of the loops, but I am sure there is a better way.

**Comment by charneykaye** [comment]
@codexnubes try out the latest version on master branch now.
